# Site information
title: My Awesome Site
description: A description of my site.
baseurl: ""  # Leave empty for the root, or set to "/<repo-name>" for a project page
url: "https://MruthuKrish.github.io"  # Replace with your GitHub username and repo name

# Theme configuration
theme: jekyll-theme-primer  # You mentioned you're using this theme

# Plugins used by GitHub Pages
plugins:
  - jekyll-seo-tag         # For SEO optimization
  - jekyll-paginate        # For pagination support
  - jekyll-github-metadata # For GitHub metadata

# Markdown settings
markdown: kramdown

# Exclude files or directories from being processed
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Permalink structure (this can be customized if needed)
permalink: /:year/:month/:day/:title/

# Optional: Customization for your site if needed
relative_links: true  # Use relative links if the site is deployed as a project page (not needed for user/organization pages)
